
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'B458A793591E01AB01BBC954A580E646'
    
_lr_action_items = {'ALL':([4,14,],[8,-6,]),'AMPM':([13,],[14,]),'LINUX':([0,],[2,]),'INTEGER':([0,10,12,],[5,11,13,]),':':([5,11,],[10,12,]),'CPU':([4,14,],[9,-6,]),'$end':([0,1,2,3,4,6,7,8,9,14,],[-9,-3,-1,0,-5,-2,-4,-8,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[3,]),'all':([0,],[1,]),'cpu':([0,],[6,]),'empty':([0,],[7,]),'time':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LINUX','start',1,'p_start','PLYmpstat.py',49),
  ('start -> cpu','start',1,'p_start','PLYmpstat.py',50),
  ('start -> all','start',1,'p_start','PLYmpstat.py',51),
  ('start -> empty','start',1,'p_start','PLYmpstat.py',52),
  ('start -> time','start',1,'p_start','PLYmpstat.py',53),
  ('time -> INTEGER : INTEGER : INTEGER AMPM','time',6,'p_time','PLYmpstat.py',58),
  ('cpu -> time CPU','cpu',2,'p_cpu','PLYmpstat.py',61),
  ('all -> time ALL','all',2,'p_all','PLYmpstat.py',64),
  ('empty -> <empty>','empty',0,'p_empty','PLYmpstat.py',67),
]
