
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E452BB6D1D996A13A59BDB8CD28AC7E2'
    
_lr_action_items = {'ALL':([0,],[2,]),'LINUX':([0,],[5,]),'CPU':([0,],[3,]),'$end':([0,1,2,3,4,5,],[-5,0,-3,-2,-4,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'empty':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LINUX','start',1,'p_start','PLYmpstat.py',39),
  ('start -> CPU','start',1,'p_start','PLYmpstat.py',40),
  ('start -> ALL','start',1,'p_start','PLYmpstat.py',41),
  ('start -> empty','start',1,'p_start','PLYmpstat.py',42),
  ('empty -> <empty>','empty',0,'p_empty','PLYmpstat.py',47),
]
