
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3E630D34656CD35CB7EF5B032C5B7FE8'
    
_lr_action_items = {'.':([5,],[7,]),'HEADER2':([0,],[1,]),'HEADER1':([0,],[3,]),'INTEGER':([4,7,],[5,8,]),'DATA':([0,],[4,]),'$end':([1,2,3,6,8,],[-2,0,-1,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[2,]),'float':([4,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> HEADER1','start',1,'p_start','PLYstarter.py',47),
  ('start -> HEADER2','start',1,'p_start','PLYstarter.py',48),
  ('start -> DATA float','start',2,'p_start','PLYstarter.py',49),
  ('float -> INTEGER . INTEGER','float',3,'p_float','PLYstarter.py',53),
]
