
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '54820A6D8FB5AA5FA5E3D4961CD92D46'
    
_lr_action_items = {'$end':([1,2,3,4,],[-3,0,-1,-2,]),'NUM':([0,1,2,3,4,],[1,-3,1,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'integer':([0,],[2,]),'digit':([0,2,],[3,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> integer","S'",1,None,None,None),
  ('integer -> digit','integer',1,'p_start','simpleGrammar.py',31),
  ('integer -> integer digit','integer',2,'p_start','simpleGrammar.py',32),
  ('digit -> NUM','digit',1,'p_digit','simpleGrammar.py',40),
]
